### ISSUE TITLE
Get Smokey working on ARM

### ISSUE THREAD

**Issue by dj-maisy** [alphagov/smokey#1303]
## What?
We want to get Smokey working on ARM.

### Sub-tasks

- [x] Switch to the multi-arch workflow.
- [x] Get Chrome/Chromium working on ARM.
- [x] Switch Integration to the ARM arch.
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/smokey/pull/1301
- [x] Configure Smokey to use ARM on Integration
```

**Comment by dj-maisy** [comment]
This is now also done.
